### ISSUE TITLE
Building with msys2/mingw64 on Windows 10

### ISSUE THREAD

**Issue by jeremiahbreeden** [Entomy/libAnne#2] opened 2019-06-06 01:45 UTC
Curious if you have any tips for compiling against the FSF version of GNAT on mingw64.  I tried cloning and doing:

gprbuild -P libAnne.gpr -p -XPlatform=Windows

Compilation went fine, but the creation of the DLL went wonky with lots of linking errors (most of them looked like stuff from the Ada runtime).

GNAT is the FSF version 8.2.0

Attaching an example of the output.
[example_libanne_mingw64.txt](https://github.com/Entomy/libAnne/files/3259639/example_libanne_mingw64.txt)

**Comment by jeremiahbreeden** [comment] 2019-06-06 01:49
The standard path variables are all correct.  I use this to build most of my Gnoga apps without any issue.  I'm guessing I need to do something special due to it being a DLL (which I haven't messed with in mingw64 yet)

**Comment by Entomy** [comment] 2019-06-06 01:53
Well I can safely say the issue is that it's not finding the current Ada standard library. `undefined reference to `system__secondary_stack__ss_allocate'` for example, is saying it can't find `System.Secondary_Stack` which is the package implementing the secondary stack used for many operations. Since there's no tasking operations being used yet, it only needs to find libgnat. That being said I'm not sure why it's not finding libgnat for you.

Can you open the DLL with [Dependencies](https://github.com/lucasg/Dependencies) or something similar? Screenshot whatever comes up. I want to see if it's correctly linking against libgnat and just can't find it, or not linking against it at all.

Unfortunantly I don't have the required System units implemented so piggybacking on libgnat and libgnarl is required for the time being.

**Comment by jeremiahbreeden** [comment] 2019-06-06 02:08
I'll work on that and get back to you with the output from Dependencies.

**Comment by jeremiahbreeden** [comment] 2019-06-07 00:21
It looks like it isn't even generating the DLL, so I can't check the dependencies.  It looks like it is dying on the step that is trying to create the DLL.  It's definitely odd that this project in particular cannot find libgnat while other ones can.  maybe mingw64 has a problem with windows DLL"s.  I'll try in GNAT Community and see if there is a difference.

**Comment by jeremiahbreeden** [comment] 2019-06-07 00:40
The GNAT Community one does build ok and has the 5 main DLL's linked in:

\GNAT\2018\bin\libgnat-2018.dll
\GNAT\2018\bin\libgnarl-2018.dll
\GNAT\2018\bin\libgcc_s_seh-1.dll
\WINDOWS\system32\kernel32.dll
\WINDOWS\system32\MSVCRT.dll

the mingw64 installation does have comparable gnat dlls as well, though named differently:
\msys64\mingw64\bin\libgnat-8.dll
\msys64\mingw64\bin\libgnarl-8.dll
\msys64\mingw64\bin\libgcc_s_seh-1.dll

**Comment by Entomy** [comment] 2019-06-07 01:48
Yeah, the different libgnat/libgnarl names is something I've known about and is okay. I had Ada-tools looking for both versioning conventions as well.

I don't know why mingw64 is giving you problems though. Unfortunantly I'm unable to test that here as my msys2 installation won't let me bootstrap gprbuild right now.

**Comment by Entomy** [comment] 2019-06-07 01:49
Wait, here's an idea. Copy libgnat-8, libgnarl-8, and libgcc_s_seh-1 into the libAnne `libraries` directory, then try building again.

**Comment by jeremiahbreeden** [comment] 2019-06-07 02:11
Yeah, I had no luck building GPRBuild in mingw64 either.  I had to borrow a copy from another GNAT installation, reconfigure it, and use that.  And that could be the source of my problems.

I tried copying the files to both the objects and the libraries directories, but no dice.  

Not a huge deal for now.  I can always statically link to the source in my GPR files to get around this.

**Comment by Entomy** [comment] 2019-06-07 02:14
You could also just dump the sources into the `ADA_INCLUDE_PATH`, and optionally the ALIs and DLLs into the `ADA_OBJECTS_PATH`. Then all projects will just find it regardless, no set up necessary.

**Comment by jeremiahbreeden** [comment] 2019-06-09 05:02
Ok, Thanks!

**Comment by Entomy** [comment] 2019-06-13 16:14
Since you haven't reported any further problems and it seems to be caused by the hacked together msys2 and gprbuild, I'm closing this question. Reopen if necessary.

**Closed by Entomy** 2019-06-13 16:14 UTC
Labels: question

**Comment by Entomy** [comment] 2019-07-25 13:21
I managed to replicate this exact issue, and it is in fact caused by the hack.
